[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
glam = { version = "0.29.2", features = ["bytemuck"] }
image = "0.25.5"
log = "0.4.22"
pollster = "0.4.0"
rustc-hash = "2.0.0"
wgpu = "23.0.0"
winit = "0.30.5"
